BittWizards/frontend

- src/app/router/router.tsx
- src/app/styles/variables.scss
- src/pages/AmbassadorDetailPage/index.ts
- src/pages/AmbassadorDetailPage/ui/AmbassadorDetailPage.module.scss
- src/pages/AmbassadorDetailPage/ui/AmbassadorDetailPage.tsx
- src/pages/PromocodePage/ui/PromocodePage.module.scss
- src/pages/PromocodePage/ui/PromocodePage.tsx
- src/utils/constants/ambassadorCardData.ts
- src/widgets/AmbassadorCard/ui/AmbassadorCard.module.scss
- src/widgets/AmbassadorCard/ui/AmbassadorCard.tsx
- src/widgets/ContentUserCard/ui/ContentUserCard.module.scss
- src/widgets/ContentUserCard/ui/ContentUserCard.tsx
- src/widgets/PromocodeUserInfoCard/index.ts
- src/widgets/PromocodeUserInfoCard/types/types.ts
- src/widgets/PromocodeUserInfoCard/ui/PromocodeUserInfoCard.module.scss
- src/widgets/PromocodeUserInfoCard/ui/PromocodeUserInfoCard.tsx
Добавлены карточки на страницу Промокоды
> feat: promopage cards added

- src/entities/AmbassadorsInfoCard/ui/AmbassadorsInfoCard.tsx
- src/entities/Avatar/index.ts
- src/entities/Avatar/types/types.ts
- src/entities/Avatar/ui/Avatar.module.scss
- src/entities/Avatar/ui/Avatar.tsx
- src/pages/MainPage/ui/MainPage.tsx
- src/shared/icons/two-left-arrow.svg
- src/widgets/AmbassadorCard/ui/AmbassadorCard.tsx
- src/widgets/AmbassadorList/ui/AmbassadorList.tsx
- src/widgets/ContentContainer/ui/ContentContainer.module.scss
- src/widgets/ContentUserCard/ui/ContentUserCard.tsx
- src/widgets/MerchUserInfoCard/ui/MerchUserInfoCard.tsx
- src/widgets/NavBar/ui/NavBar.module.scss
- src/widgets/NavBar/ui/NavBar.tsx
- src/widgets/PromocodeUserInfoCard/ui/PromocodeUserInfoCard.tsx
- add component avatar
- add hover effect to links
- add avatar to navbar
> feat: navbarProfile

- src/widgets/AmbassadorCard/ui/AmbassadorCard.module.scss
- src/widgets/ContentUserCard/ui/ContentUserCard.module.scss
- src/widgets/MerchUserInfoCard/ui/MerchUserInfoCard.module.scss
- src/widgets/PromocodeUserInfoCard/ui/PromocodeUserInfoCard.module.scss
- Добавил box-sizing к карточкам
> fix: cardsSize

- src/entities/ButtonGray/index.ts
- src/entities/ButtonGray/types/types.ts
- src/entities/ButtonGray/ui/ButtonGray.module.scss
- src/entities/ButtonGray/ui/ButtonGray.tsx
> feat: Button Gray

- src/entities/AmbassadorHeaderCard/ui/AmbassadorHeaderCard.tsx
- src/pages/AmbassadorPage/ui/AmbassadorPage.tsx
- src/pages/PromocodePage/ui/PromocodePage.tsx
- src/shared/StatusIcon/index.ts
- src/shared/StatusIcon/types/type.ts
- src/shared/StatusIcon/ui/StatusIcon.module.scss
- src/shared/StatusIcon/ui/StatusIcon.tsx
- src/utils/constants/ambassadorCardData.ts
- src/widgets/AmbassadorCard/ui/AmbassadorCard.tsx
- src/widgets/AmbassadorTable/ui/AmbassadorTable.tsx
- src/widgets/ContentUserCard/ui/ContentUserCard.tsx
- src/widgets/MerchUserInfoCard/types/types.ts
- src/widgets/MerchUserInfoCard/ui/MerchUserInfoCard.tsx
- src/widgets/PromocodeUserInfoCard/types/types.ts
- src/widgets/PromocodeUserInfoCard/ui/PromocodeUserInfoCard.tsx
Добавлен компонент для отображения статуса в разных состояниях
> ref: add status component

- src/entities/MerchStatisticTable/index.ts
- src/entities/MerchStatisticTable/ui/MerchStatisticTable.module.scss
- src/entities/MerchStatisticTable/ui/MerchStatisticTable.tsx
- src/pages/MerchPage/ui/MerchPage.module.scss
- src/pages/MerchPage/ui/MerchPage.tsx
- src/utils/constants/ambassadorCardData.ts
- src/widgets/AmbassadorTable/ui/AmbassadorTable.tsx
> feat: added merch statistic table

- src/pages/AmbassadorMerchPage/ui/AmbassadorMerchPage.tsx
- src/pages/ContentPage/ui/ContentPage.tsx
- src/pages/MailingPage/model/data.ts
- src/pages/MailingPage/ui/MailingPage.module.scss
- src/pages/MailingPage/ui/MailingPage.tsx
Добавлены табы на странице рассылок
> feat:added mailing page header

- package-lock.json
- package.json
- src/entities/Button/index.ts
- src/pages/AmbassadorContentPage/ui/AmbassadorContentPage.tsx
- src/pages/AmbassadorMerchPage/ui/AmbassadorMerchPage.tsx
- src/pages/AmbassadorPage/ui/AmbassadorPage.module.scss
- src/pages/AmbassadorPage/ui/AmbassadorPage.tsx
- src/pages/AmbassadorPromocodePage/ui/AmbassadorPromocodePage.tsx
- src/pages/MailingPage/ui/MailingPage.module.scss
- src/pages/MailingPage/ui/MailingPage.tsx
- src/pages/PromocodePage/ui/PromocodePage.module.scss
- src/pages/PromocodePage/ui/PromocodePage.tsx
- src/utils/constants/allMailingData.ts
- src/widgets/AmbassadorTable/ui/AmbassadorTable.tsx
- src/widgets/MailingDataGrid/index.ts
- src/widgets/MailingDataGrid/ui/MailingDataGrid.module.scss
- src/widgets/MailingDataGrid/ui/MailingDataGrid.tsx
- src/widgets/NavBar/index.ts
Добавлена таблица на страницу всех рассылок
> feat: add all mail page

- src/app/router/router.tsx
- src/pages/MainPage/ui/MainPage.tsx
- src/pages/StatsPage/ui/StatsPage.tsx
- src/widgets/ContentContainer/index.ts
- src/widgets/StatisticsAnalyticsContainer/index.ts
export default  замененны на именованный export
> refactoring

- src/app/styles/variables.scss
- src/entities/PromoInfoCard/model/data.ts
- src/entities/PromoInfoCard/ui/PromoInfoCard.tsx
Добавлены разные цвета для рендеринга бордера карточке Промокодов (4 цвета)
> ref: add different colors promocode main page

- src/entities/Modals/ChoiceModal/ChoiceModal.module.scss
- src/entities/Modals/ChoiceModal/ChoiceModal.tsx
- src/entities/Modals/InputModal/InputModal.module.scss
- src/entities/Modals/InputModal/InputModal.tsx
- src/entities/Modals/SuccessModal/SuccessModal.module.scss
- src/entities/Modals/SuccessModal/SuccessModal.tsx
- src/entities/Modals/index.ts
- src/pages/PromocodePage/ui/PromocodePage.tsx
Добавлено два типа модальных окон
> feat: add modals

- src/entities/QuestionnaireProfileInfo/ui/QuestionnaireProfileInfo.module.scss
- src/entities/QuestionnaireProfileInfo/ui/QuestionnaireProfileInfo.tsx
> fix: questionareProfile

- src/entities/Modals/ChoiceModal/ChoiceModal.module.scss
- src/entities/Modals/ChoiceModal/ChoiceModal.tsx
- src/entities/Modals/InputModal/InputModal.module.scss
- src/entities/Modals/InputModal/InputModal.tsx
- src/entities/Modals/SuccessModal/SuccessModal.module.scss
- src/entities/Modals/SuccessModal/SuccessModal.tsx
- src/entities/Modals/index.ts
- src/pages/AmbassadorPromocodePage/ui/AmbassadorPromocodePage.module.scss
- src/pages/AmbassadorPromocodePage/ui/AmbassadorPromocodePage.tsx
- src/shared/icons/closeButton.svg
Модальные окна привязаны к табу с промокодами
> feat: modals added to promocod

- src/entities/user/index.ts
- src/entities/user/model/types/User.ts
- src/pages/AmbassadorPage/ui/AmbassadorPage.module.scss
- src/pages/AmbassadorPage/ui/AmbassadorPage.tsx
- src/utils/constants/mockCardsData.ts
- src/widgets/AmbassadorCard/ui/AmbassadorCard.module.scss
- src/widgets/AmbassadorCard/ui/AmbassadorCard.tsx
- src/widgets/NavBar/ui/NavBar.module.scss
> ref: styles

- src/entities/Modals/DateInputModal/ui/DateInputModal.module.scss
- src/entities/Modals/DateInputModal/ui/DateInputModal.tsx
- src/entities/Modals/index.ts
- src/pages/AmbassadorPromocodePage/ui/AmbassadorPromocodePage.tsx
- src/shared/StatusIcon/ui/StatusIcon.module.scss
- src/widgets/MerchUserInfoCard/ui/MerchUserInfoCard.module.scss
- src/widgets/MerchUserInfoCard/ui/MerchUserInfoCard.tsx
Добавлено модальное окно с выбором даты, исправлена верстка карточек "Мерч"
> feat: add modal with date input

- src/app/store/reducers/contents/index.ts
- src/app/store/reducers/contents/model/contentsSlice.ts
- src/app/store/store.ts
- src/pages/AmbassadorPage/ui/AmbassadorPage.tsx
- src/pages/ContentPage/ui/ContentPage.tsx
- src/shared/api/contents/dtos.ts
- src/shared/api/contents/index.ts
- src/widgets/ContentUserCard/types/types.ts
- src/widgets/ContentUserCard/ui/ContentUserCard.tsx
Получаются данные с бэка о новом контенте
> feat: add new content reducer

- src/app/store/reducers/merch/model/merchSlice.ts
- src/app/store/reducers/orders/imdex.ts
- src/app/store/reducers/orders/model/ordersSlice.ts
- src/app/store/store.ts
- src/entities/MerchStatisticTable/types/type.ts
- src/entities/MerchStatisticTable/ui/MerchStatisticTable.tsx
- src/pages/MerchPage/model/sortFunctions.ts
- src/pages/MerchPage/ui/MerchPage.tsx
- src/shared/api/merch/dtos.ts
- src/shared/api/merch/index.ts
- src/shared/api/orders/dtos.ts
- src/shared/api/orders/index.ts
- src/widgets/MerchUserInfoCard/types/types.ts
- src/widgets/MerchUserInfoCard/ui/MerchUserInfoCard.module.scss
- src/widgets/MerchUserInfoCard/ui/MerchUserInfoCard.tsx
Добавлено получение данных о заказах и таблица истории мерча
> feat: added api data merch and orders

- src/app/store/reducers/contents/model/const.ts
- src/app/store/reducers/contents/model/contentsSlice.ts
- src/app/store/reducers/promocodes/model/cont.ts
- src/app/store/reducers/promocodes/model/promocodesSlice.ts
- src/entities/AmbassadorHeaderCard/types/types.ts
- src/entities/AmbassadorHeaderCard/ui/AmbassadorHeaderCard.tsx
- src/pages/AmbassadorContentPage/ui/AmbassadorContentPage.tsx
- src/pages/AmbassadorPromocodePage/ui/AmbassadorPromocodePage.tsx
- src/shared/api/content/dtos.ts
- src/shared/api/content/index.ts
- src/shared/api/promocodes/dtos.ts
- src/shared/api/promocodes/index.ts
> feat: add api

- src/pages/MerchPage/ui/MerchPage.tsx
- src/widgets/MerchUserInfoCard/ui/MerchUserInfoCard.tsx
- src/widgets/PromocodeUserInfoCard/ui/PromocodeUserInfoCard.tsx
Исправлены пути в навигации, передавался не тот id
> fix: navigation id fixed

- src/pages/AmbassadorPromocodePage/ui/AmbassadorPromocodePage.module.scss
- src/pages/AmbassadorPromocodePage/ui/AmbassadorPromocodePage.tsx
- src/shared/InfoLogoLink/model/formatTel.ts
- src/shared/InfoLogoLink/ui/InfoLogoLink.tsx
- src/shared/SubtitleWithEditBtn/types/type.ts
- src/shared/SubtitleWithEditBtn/ui/SubtitleWithEditBtn.tsx
Обновлены стили вкладки промокоды амбассадора
> ref: promocode styles

- src/entities/Activity/types/types.ts
- src/entities/Activity/ui/Activity.tsx
- src/entities/Contacts/types/types.ts
- src/entities/Contacts/ui/Contacts.tsx
- src/entities/DataMerch/types/types.ts
- src/entities/DataMerch/ui/DataMerch.tsx
- src/entities/PostalDetails/types/types.ts
- src/entities/PostalDetails/ui/PostalDetails.tsx
- src/entities/QuestionnaireForm/types/types.ts
- src/entities/QuestionnaireForm/ui/QuestionnaireForm.tsx
- src/entities/QuestionnaireProfileInfo/types/types.ts
- src/entities/QuestionnaireProfileInfo/ui/QuestionnaireProfileInfo.tsx
- src/entities/WorkAndEducation/types/types.ts
- src/entities/WorkAndEducation/ui/WorkAndEducation.tsx
- src/pages/AmbassadorDetailPage/ui/AmbassadorDetailPage.tsx
- src/pages/CandidateDetailPage/ui/CandidateDetailPage.tsx
- src/pages/NewAmbassadorPage/ui/NewAmbassadorPage.tsx
- src/shared/Checkbox/types/types.ts
- src/shared/Checkbox/ui/Checkbox.tsx
- src/shared/Input/types/types.ts
- src/shared/Input/ui/Input.tsx
- src/shared/Textarea/types/types.ts
- src/shared/Textarea/ui/Textarea.tsx
- src/widgets/AmbassadorQuestionnaire/ui/AmbassadorQuestionnaire.tsx
- src/widgets/CandidateQuestionnaire/ui/CandidateQuestionnaire.tsx
add isEdit and isEditable to questionnaires
> fix: questionnaire

- src/widgets/AllContentCard/ui/AllContentCard.tsx
Небольшие правки по просьбам наставника
> Minor fixes

- src/entities/MerchStatisticTable/ui/MerchStatisticTable.module.scss
- src/entities/MerchStatisticTable/ui/MerchStatisticTable.tsx
- src/pages/AmbassadorPage/ui/AmbassadorPage.tsx
- src/pages/MerchPage/ui/MerchPage.tsx
> ref: merch rable styles and render

- src/entities/QuestionnaireForm/ui/QuestionnaireForm.tsx
- src/entities/QuestionnaireProfileInfo/ui/QuestionnaireProfileInfo.tsx
- src/pages/AmbassadorDetailPage/ui/AmbassadorDetailPage.tsx
- src/pages/AmbassadorMerchPage/ui/AmbassadorMerchPage.tsx
- src/pages/CandidateDetailPage/ui/CandidateDetailPage.tsx
- src/shared/Checkbox/ui/Checkbox.tsx
- src/shared/Input/ui/Input.tsx
- src/shared/Textarea/ui/Textarea.tsx
- src/shared/api/orders/dtos.ts
- src/widgets/AllContentCard/ui/AllContentCard.tsx
- src/widgets/AmbassadorQuestionnaire/ui/AmbassadorQuestionnaire.tsx
- src/widgets/CandidateQuestionnaire/ui/CandidateQuestionnaire.tsx
Рендер таба мерч, подсчет общей суммы
> ref: merch tab render and api

- src/app/store/reducers/orders/model/const.ts
- src/app/store/reducers/promocodes/model/promocodesSlice.ts
- src/entities/Modals/InputModal/InputModal.tsx
- src/pages/AmbassadorPromocodePage/ui/AmbassadorPromocodePage.tsx
- src/shared/api/promocodes/dtos.ts
- src/shared/api/promocodes/index.ts
Удление и изменение промокодов добавлено на там Промокоды
> feat: promo change and delete added

- src/app/ui/App.tsx
- src/widgets/NavBar/ui/NavBar.tsx
Уведомления при загрузке страницы
> fix: notification effect

- src/app/store/reducers/ambassadors/model/constants.ts
- src/entities/AmbassadorHeaderCard/types/types.ts
- src/entities/AmbassadorHeaderCard/ui/AmbassadorHeaderCard.tsx
- src/entities/AmbassadorsInfoCard/ui/AmbassadorsInfoCard.tsx
- src/entities/Avatar/ui/Avatar.tsx
- src/entities/MerchStatisticTable/ui/MerchStatisticTable.tsx
- src/entities/QuestionnaireProfileInfo/ui/QuestionnaireProfileInfo.tsx
- src/shared/api/ambassadors/dtos.ts
- src/shared/api/content/dtos.ts
- src/shared/api/merch/dtos.ts
- src/shared/api/orders/dtos.ts
- src/shared/api/promocodes/dtos.ts
- src/widgets/AllContentCard/ui/AllContentCard.tsx
- src/widgets/AmbassadorCard/ui/AmbassadorCard.tsx
- src/widgets/AmbassadorTable/ui/AmbassadorTable.tsx
- src/widgets/ContentUserCard/ui/ContentUserCard.tsx
- src/widgets/MerchUserInfoCard/ui/MerchUserInfoCard.tsx
- src/widgets/PromocodeUserInfoCard/ui/PromocodeUserInfoCard.tsx
Добавление функционала achievement
> feat: add avatars achievements

- Dockerfile
> Added permissions for entrypoint
